### ISSUE TITLE
Implementation of #1324 feature request. Environment variables starting with `nginx_*` are added as nginx config statements, for example: `nginx_client_max_body_size=30M`. Variables of jwilder/nginx-proxy container are added to the global config, and variables on others containers are added to the respective vhosts.

### ISSUE THREAD

**Issue by VPS-Crypto** [sonatype/docker-nexus#135]
Implementation of #1324 feature request. Environment variables starting with `nginx_*` are added as nginx config statements, for example: `nginx_client_max_body_size=30M`. Variables of jwilder/nginx-proxy container are added to the global config, and variables on others containers are added to the respective vhosts.

Example `docker-compose.yml`:

```yaml
version: '2.1'

services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      nginx_client_max_body_size: 42M

  app:
    image: app
    environment:
      VIRTUAL_HOST: example.com
      nginx_client_max_body_size: 1337M
```

Currently only lower case variables are supported (until jwilder/docker-gen#306 is merged). Also if there is an easy way to merge `Env` dicts from all containers with the same vhost, we should do that, currently `Env` map is taken from the first container for each vhost.

__Originally posted by @poma in https://github.com/nginx-proxy/nginx-proxy/pull/1326__
